version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '6033:3306'
    volumes:
      - ./data/db/mysql:/var/lib/mysql
